Controllers/BookController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookShop.Areas.Identity.Data;
using BookShop.Models;
using Microsoft.AspNetCore.Identity;

namespace BookShop.Controllers
{
    public class BookController : Controller
    {
        private readonly UserContext _context;
        private readonly UserManager<BookShopUser> _userManager;

        public BookController(UserContext context, UserManager<BookShopUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Book
        public async Task<IActionResult> Index()
        {
            var userContext = _context.Books.Include(b => b.Category).Include(b => b.User);
            return View(await userContext.ToListAsync());
        }

        // GET: Book/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.Category)
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.Isbn == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Book/Create
        public IActionResult Create()
        {
            var userid = _userManager.GetUserId(HttpContext.User);
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            ViewData["Id"] = _context.Users.Where(c => c.Id == userid).FirstOrDefault().UserName;
            return View();
        }

        // POST: Book/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Isbn,Title,Pages,Author,Price,Desc,ImgUrl,CategoryId")] Book book, IFormFile image)
        {
            var userid = _userManager.GetUserId(HttpContext.User);

            if (image != null)
            {
                string imgName = book.Isbn + Path.GetExtension(image.FileName);
                string savePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", imgName);
                using (var stream = new FileStream(savePath, FileMode.Create))
                {
                    image.CopyTo(stream);
                }
                book.ImgUrl = imgName;
            }
            else
            {
                return View(book);
            }

            if (ModelState.IsValid)
            {
                book.UId = userid;
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", book.CategoryId);
            ViewData["Id"] = _context.Users.Where(c => c.Id == userid).FirstOrDefault().UserName;
            return View(book);
        }

        // GET: Book/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", book.CategoryId);
            ViewData["UId"] = new SelectList(_context.Users, "Id", "Id", book.UId);
            return View(book);
        }

        // POST: Book/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Isbn,Title,Pages,Author,Price,Desc,ImgUrl,CategoryId,UId")] Book book)
        {
            if (id != book.Isbn)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.Isbn))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", book.CategoryId);
            ViewData["UId"] = new SelectList(_context.Users, "Id", "Id", book.UId);
            return View(book);
        }

        // GET: Book/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.Category)
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.Isbn == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Book/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var book = await _context.Books.FindAsync(id);
            _context.Books.Remove(book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(string id)
        {
            return _context.Books.Any(e => e.Isbn == id);
        }
    }
}

Controllers/OrdersController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookShop.Areas.Identity.Data;
using BookShop.Models;
using Microsoft.AspNetCore.Identity;

namespace BookShop.Controllers
{
    public class OrdersController : Controller
    {
        private readonly UserContext _context;
        private readonly UserManager<BookShopUser> _userManager;
        public OrdersController(UserContext context, UserManager<BookShopUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
             var userid = _userManager.GetUserId(HttpContext.User);
            var userContext = _context.Orders
                .Include(q => q.OrderDetails).ThenInclude(a => a.Book)
                .Include(o => o.User)
                .Where(r => r.UId == userid);
               
            

            return View(await userContext.ToListAsync());
        }

        
    }
}

Views/Shared/_BlankLayout.cshtml
@RenderBody()
     

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="vi">

<head>
    <title>FPTbook-Mua sách trực tuyến giá rẻ nhất</title>
    <meta name="description"
        content="Mua sách online hay, giá tốt nhất, combo sách hot bán chạy, giảm giá cực khủng cùng với những ưu đãi như miễn phí giao hàng, quà tặng miễn phí, đổi trả nhanh chóng. Đa dạng sản phẩm, đáp ứng mọi nhu cầu.">
    <meta name="keywords" content="nhà sách online, mua sách hay, sách hot, sách bán chạy, sách giảm giá nhiều">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet"  href="~/Layoutforcustomer/css/home.css">
    <script type="text/javascript"  src="~/Layoutforcustomer/js/main.js"></script>
    <link rel="stylesheet"  href="~/Layoutforcustomer/fontawesome_free_5.13.0/css/all.css">

    <link  href="~/Layoutforcustomer/https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap"
        rel="stylesheet">

    <link rel="stylesheet" type="text/css"  href="~/Layoutforcustomer/slick/slick.css" />
    <link rel="stylesheet" type="text/css"  href="~/Layoutforcustomer/slick/slick-theme.css" />
    <script type="text/javascript"  src="~/Layoutforcustomer/slick/slick.min.js"></script>
    <script type="text/javascript"
        src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js"></script>
    <link rel="canonical" href="http://dealbook.xyz/">
    <meta name="google-site-verification" content="urDZLDaX8wQZ_-x8ztGIyHqwUQh2KRHvH9FhfoGtiEw" />
    <link rel="apple-touch-icon" sizes="180x180"  href="~/Layoutforcustomer/favicon_io/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32"  href="~/Layoutforcustomer/favicon_io/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16"  href="~/Layoutforcustomer/favicon_io/favicon-16x16.png">
    <link rel="manifest"  href="~/Layoutforcustomer/favicon_io/site.webmanifest">
    <style>img[alt="www.000webhost.com"]{display: none;}</style>
</head>

<body>
    <!-- code cho nut like share facebook  -->
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous"
        src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v6.0"></script>

    <!-- header -->
    <nav class="navbar navbar-expand-md bg-white navbar-light">
        <div class="container">
            <!-- logo  -->
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color: #CF111A;"><b>FPT-Book</b></a>

            <!-- navbar-toggler  -->
            <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse"
                data-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false"
                aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

            <li class="collapse navbar-collapse" id="collapsibleNavId">
                <!-- form tìm kiếm  -->

                <form asp-controller="Book" asp-action="Index" method="get" class="form-inline ml-auto my-2 my-lg-0 mr-3">
                    <div class="input-group" style="width: 520px;">
                        <input type="text" name="StringSearch" value="@ViewData["CurrentFilter"]" class="form-control" aria-label="Small"
                            placeholder="Nhập sách cần tìm kiếm...">
                        <div class="input-group-append">
                            <button type="button" class="btn" style="background-color: #CF111A;">
                              
                                    <input style="background-color: #CF111A; border:none" type="submit" value="Search" class="submit-search" asp-route-id="0" asp-route-StringSearch="@ViewData["CurrentFilter"]" >
                               
                            </button>
                        </div>
                    </div>
                </form>



               
	
	




                <!-- ô đăng nhập đăng ký giỏ hàng trên header  -->
                <ul class="navbar-nav mb-1 ml-auto">
                    <div class="dropdown">
                        <li class="nav-item account" type="button" class="btn dropdown" data-toggle="dropdown">
                            <a href="#" class="btn btn-secondary rounded-circle">
                                <i class="fa fa-user"></i>
                            </a>
                            <a class="nav-link text-dark text-uppercase" href="#" style="display:inline-block">Tài
                                khoản</a>
                        </li>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                             <partial name="_LoginPartial" />
                        </div>
                    </div>
                    <li class="nav-item giohang">
                        <a asp-controller="Carts" asp-action="Index" class="btn btn-secondary rounded-circle">
                            <i class="fa fa-shopping-cart"></i>
                            
                        </a>
                        <a asp-controller="Carts" asp-action="Index" class="nav-link text-dark giohang text-uppercase" 
                            style="display:inline-block">Giỏ
                            Hàng</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Orders" asp-action="Index" class="nav-link text-dark giohang text-uppercase" 
                            style="display:inline-block">ORDERS HISTORY</a>
                    </li> 
                    
                     <li>
                           <a class="nav-link text-dark" asp-area="Seller" asp-controller="Home" asp-action="Index">YOUR STORE</a>
                     </li>

                </ul>



            </div>
        </div>
    </nav>
    
 
    @RenderBody()
    


   

    <!-- footer  -->
   <div class="mt-auto">

	@*<footer class="bg3 p-t-75 p-b-32 mt-auto">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-xs-6">
                    <div class="gioithieu">
                        <h3 class="header text-uppercase font-weight-bold">Về DealBook</h3>
                        <a href="#">Giới thiệu về DealBook</a>
                        <a href="#">Tuyển dụng</a>
                        <div class="fb-like" data-href="https://www.facebook.com/DealBook-110745443947730/"
                            data-width="300px" data-layout="button" data-action="like" data-size="small"
                            data-share="true"></div>
                    </div>
                </div>
                <div class="col-md-3 col-xs-6">
                    <div class="hotrokh">
                        <h3 class="header text-uppercase font-weight-bold">HỖ TRỢ KHÁCH HÀNG</h3>
                        <a href="#">Hướng dẫn đặt hàng</a>
                        <a href="#">Phương thức thanh toán</a>
                        <a href="#">Phương thức vận chuyển</a>
                        <a href="#">Chính sách đổi trả</a>
                    </div>
                </div>
                <div class="col-md-3 col-xs-6">
                    <div class="lienket">
                        <h3 class="header text-uppercase font-weight-bold">HỢP TÁC VÀ LIÊN KẾT</h3>
                        <img  src="~/Layoutforcustomer/images/dang-ky-bo-cong-thuong.png" alt="dang-ky-bo-cong-thuong">
                    </div>
                </div>
                <div class="col-md-3 col-xs-6">
                    <div class="ptthanhtoan">
                        <h3 class="header text-uppercase font-weight-bold">Phương thức thanh toán</h3>
                        <img  src="~/Layoutforcustomer/images/visa-payment.jpg" alt="visa-payment">
                        <img  src="~/Layoutforcustomer/images/master-card-payment.jpg" alt="master-card-payment">
                        <img  src="~/Layoutforcustomer/images/jcb-payment.jpg" alt="jcb-payment">
                        <img  src="~/Layoutforcustomer/images/atm-payment.jpg" alt="atm-payment">
                        <img  src="~/Layoutforcustomer/images/cod-payment.jpg" alt="cod-payment">
                        <img  src="~/Layoutforcustomer/images/payoo-payment.jpg" alt="payoo-payment">
                    </div>
                </div>
            </div>
        </div>
    </footer>*@

    <!-- nut cuon len dau trang -->
 
    </div>

</body>

</html>

@await RenderSectionAsync("Scripts", required: false)