Models/Order.cs
using BookShop.Areas.Identity.Data;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BookShop.Models
{
    public class Order
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string UId { get; set; }
        public DateTime OrderDate { get; set; }
        public int Total { get; set; }
        public BookShopUser User { get; set; }
        public virtual ICollection<OrderDetail>? OrderDetails { get; set; }

    }
}

Areas/Seller/Controllers/OrdersController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookShop.Areas.Identity.Data;
using BookShop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace BookShop.Areas.Seller.Controllers
{
    [Area("Seller")]
    [Authorize(Roles = "Seller")]
    public class OrdersController : Controller
    {
        private readonly UserContext _context;
        private readonly UserManager<BookShopUser> _userManager;
        public OrdersController(UserContext context, UserManager<BookShopUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Seller/Orders
        public async Task<IActionResult> Index()
        {
            var userid = _userManager.GetUserId(HttpContext.User);
            var userContext = _context.Orders.Include(o => o.User)
                .Where(s => s.OrderDetails.Where(d => d.Book.UId == userid).Any());



            return View(await userContext.ToListAsync());
        }
    }
}

Controllers/OrderDetailsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookShop.Areas.Identity.Data;
using BookShop.Models;

namespace BookShop.Controllers
{
    public class OrderDetailsController : Controller
    {
        private readonly UserContext _context;

        public OrderDetailsController(UserContext context)
        {
            _context = context;
        }

        // GET: OrderDetails
        public async Task<IActionResult> Index(int id)
        {
            var userContext = _context.OrderDetails.Include(o => o.Book).Include(o => o.Order)
                .Where(d => d.OrderId == id);
            return View(await userContext.ToListAsync());
        }
    }
}

Controllers/OrdersController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookShop.Areas.Identity.Data;
using BookShop.Models;
using Microsoft.AspNetCore.Identity;

namespace BookShop.Controllers
{
    public class OrdersController : Controller
    {
        private readonly UserContext _context;
        private readonly UserManager<BookShopUser> _userManager;
        public OrdersController(UserContext context, UserManager<BookShopUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
             var userid = _userManager.GetUserId(HttpContext.User);
            var userContext = _context.Orders
                .Include(q => q.OrderDetails).ThenInclude(a => a.Book)
                .Include(o => o.User)
                .Where(r => r.UId == userid);
               
            

            return View(await userContext.ToListAsync());
        }

        
    }
}

Views/Orders/Index.cshtml
@model IEnumerable<BookShop.Models.Order>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>


<table class="table">
    <thead>
        <tr>
             <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderDate)
            </th>
          
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderDate)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.User.UserName)
            </td>
            <td>
               
                <a asp-controller="OrderDetails" asp-action="Index" asp-route-id="@item.Id">Details</a> 
              
            </td>
        </tr>
}
    </tbody>
</table>